"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { ActivityConfig, ActivityStatus, ActivitySummary } from "@/lib/types";
export const duration = (seconds: number) => seconds >= 3600 ? `${(seconds/3600).toFixed(1)} h` : seconds >= 60 ? `${Math.round(seconds/60)} min` : `${Math.round(seconds)} s`;
export function ActivityPanel({ onClose, onOpen, onChanged }: { onClose: () => void; onOpen: (id: number) => void; onChanged: () => Promise<void> }) {
 const [status,setStatus]=useState<ActivityStatus|null>(null),[summary,setSummary]=useState<ActivitySummary|null>(null),[draft,setDraft]=useState<ActivityConfig|null>(null);
 const [days,setDays]=useState(1),[error,setError]=useState(""),[busy,setBusy]=useState(false),[token,setToken]=useState("");
 useEffect(()=>{let active=true;const load=async()=>{try{const [s,u]=await Promise.all([api.activity(),api.activitySummary(days)]);if(active){setStatus(s);setSummary(u);setDraft(d=>d??s.config);}}catch(e){if(active)setError(String(e));}};load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer);};},[days]);
 const run=async(action:()=>Promise<void>)=>{setBusy(true);setError("");try{await action();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const save=async(cfg:ActivityConfig)=>{const s=await api.configureActivity(cfg);setStatus(s);setDraft(s.config);await onChanged();};
 const max=Math.max(1,...(summary?.usage.map(u=>u.total_seconds)??[]));
 return <section className="activity-panel" aria-label="Activity dashboard"><header><div><h2>Activity & automatic graph</h2><p>{status?.config.enabled?"● Background recording enabled":"○ Recording stopped"} · {status?.browser_connected?"Browser connected":"Browser extension not connected"}</p></div><button onClick={onClose}>Close activity</button></header>
  {error&&<p role="alert" className="error">{error}</p>}
  {status&&<div className="privacy"><button disabled={busy} onClick={()=>run(()=>save({...status.config,enabled:!status.config.enabled}))}>{status.config.enabled?"Stop recording":"Resume recording"}</button><span>Local only · no keystrokes, screenshots, or page contents · {status.config.retention_days}-day retention</span></div>}
  {status&&!status.supported&&<p className="error">Native foreground tracking requires macOS with cgo enabled.</p>}
  {status?.warning&&<p role="status" className="warning">{status.warning}</p>}
  <label>Time range <select aria-label="Activity time range" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Last 24 hours</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select></label>
  {summary&&<><div className="metrics"><div><strong>{duration(summary.total_seconds)}</strong><span>Foreground time</span></div><div><strong>{duration(summary.active_seconds)}</strong><span>Active time</span></div><div><strong>{Math.round(summary.active_ratio*100)}%</strong><span>Active ratio</span></div><div><strong>{duration(Math.max(0,summary.total_seconds-summary.active_seconds))}</strong><span>Idle time</span></div></div>
   <h3>What you use</h3>{!summary.usage.length&&<p>No recorded usage yet. Leave Dendrite&apos;s backend running and use your apps; the first interval appears after two samples.</p>}
   <div className="usage">{summary.usage.map(u=><button key={u.title} disabled={!u.node_id} onClick={()=>onOpen(u.node_id)}><span>{u.title}</span><div className="bar"><div style={{width:`${u.total_seconds/max*100}%`}}><i style={{width:`${u.total_seconds?u.active_seconds/u.total_seconds*100:0}%`}}/></div></div><small>{duration(u.active_seconds)} active / {duration(u.total_seconds)} total · {u.sessions} sessions</small></button>)}</div>
   <h3>Recent timeline</h3><div className="timeline">{summary.recent.map(s=><div key={s.id}><time>{new Date(s.started_at).toLocaleTimeString()}</time><strong>{s.app}</strong><span>{s.window_title||s.domain||"Application focus"}</span><small>{duration(s.active_seconds)} active / {duration(s.total_seconds)} total</small>{s.domain&&<small>{s.domain}</small>}</div>)}</div></>}
  {draft&&<details><summary>Privacy, retention & browser setup</summary><fieldset disabled={busy}><label><input type="checkbox" checked={draft.window_titles} onChange={e=>setDraft({...draft,window_titles:e.target.checked})}/>Record window titles (can contain private information)</label><label><input type="checkbox" checked={draft.browser_pages} onChange={e=>setDraft({...draft,browser_pages:e.target.checked})}/>Record browser domains and sanitized page URLs</label><label>Idle threshold (seconds)<input aria-label="Idle threshold" type="number" min={15} max={900} value={draft.idle_seconds} onChange={e=>setDraft({...draft,idle_seconds:Number(e.target.value)})}/></label><label>Keep history (days)<input aria-label="Activity retention days" type="number" min={1} max={365} value={draft.retention_days} onChange={e=>setDraft({...draft,retention_days:Number(e.target.value)})}/></label><label>Excluded app names or bundle IDs (one per line)<textarea aria-label="Excluded apps" value={draft.excluded_apps.join("\n")} onChange={e=>setDraft({...draft,excluded_apps:e.target.value.split("\n")})}/></label><label>Excluded domains (includes subdomains)<textarea aria-label="Excluded domains" value={draft.excluded_domains.join("\n")} onChange={e=>setDraft({...draft,excluded_domains:e.target.value.split("\n")})}/></label><button onClick={()=>run(()=>save(draft))}>Save tracking settings</button>
   <p>Exclusions affect future samples, not existing history. Pausing is remembered across restarts. Window titles require macOS Accessibility permission. Browser page metadata is best-effort natively; install the unpacked extension from browser-extension for Chromium browsers.</p><button onClick={()=>run(async()=>setToken((await api.activityPairing()).token))}>Show browser pairing token</button>{token&&<textarea aria-label="Browser pairing token" readOnly value={token}/>}<p>Paste this private token into the extension&apos;s options and enable it. Private tabs are skipped; only the active tab of the focused browser window is reported.</p><button className="danger" onClick={()=>run(async()=>{if(!confirm("Permanently delete all activity sessions and activity graph nodes? This cannot be undone."))return;await api.clearActivity();setSummary(await api.activitySummary(days));await onChanged();})}>Delete activity history</button></fieldset></details>}
  <style jsx>{`.activity-panel{padding:20px;overflow:auto;flex:1;background:var(--bg);display:flex;flex-direction:column;gap:16px;min-width:0}header{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}header p,.privacy span{font-size:12px;color:var(--text-dim);margin-top:5px}.privacy{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.warning{padding:12px;border:1px solid #896328;background:#2b2417;font-size:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metrics div{padding:16px;background:var(--bg-panel);border:1px solid var(--border);border-radius:8px;display:flex;flex-direction:column;gap:5px}.metrics strong{font-size:22px}.metrics span{font-size:12px;color:var(--text-dim)}h3{font-size:14px}.usage{display:flex;flex-direction:column;gap:8px}.usage button{text-align:left;display:grid;grid-template-columns:minmax(80px,160px) 1fr;gap:8px}.usage small{grid-column:1/-1;color:var(--text-dim)}.bar{background:var(--bg);border-radius:4px;overflow:hidden;height:12px;margin-top:4px}.bar>div{height:100%;background:#8b93a7}.bar i{display:block;height:100%;background:var(--accent)}.timeline{display:flex;flex-direction:column;gap:8px;max-height:300px;overflow:auto}.timeline>div{display:flex;gap:8px;flex-wrap:wrap;padding:10px;border:1px solid var(--border);border-radius:6px}.timeline span{flex:1;min-width:140px;overflow-wrap:anywhere}.timeline small,.timeline time{color:var(--text-dim);font-size:12px}details{border:1px solid var(--border);padding:12px;border-radius:8px}summary{cursor:pointer}fieldset{border:0;display:flex;flex-direction:column;gap:12px;padding-top:16px}label{display:flex;align-items:center;gap:8px;flex-wrap:wrap;font-size:13px}textarea{width:100%;min-height:70px}fieldset p{font-size:12px;color:var(--text-dim);line-height:1.5}.danger{color:var(--danger)}input[type=number]{width:100px}select{background:var(--bg-panel);color:var(--text);padding:6px;border:1px solid var(--border);border-radius:6px}@media(max-width:760px){.metrics{grid-template-columns:repeat(2,1fr)}.activity-panel{padding:12px}header h2{font-size:18px}}`}</style>
 </section>;
}
