import { test, expect } from "@playwright/test";

test("V1 note, graph, edge, search, conflicts and history workflow", async ({ page }) => {
 const errors: string[] = [];
 page.on("pageerror", error => errors.push(error.message));
 await page.goto("/");
 const create = async (title: string, body: string) => {
  await page.getByRole("button", { name: "＋ New note" }).click();
  await page.getByLabel("Note title", { exact: true }).fill(title);
  await page.getByLabel("Markdown content").fill(body);
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await expect(page.locator(".inspector h2")).toHaveText(title);
 };
 await create("E2E Alpha", "[[E2E Beta]] #test");
 await create("E2E Beta", "Different text");
 await expect(page.locator(".status")).toContainText("2 notes");
 const graph = await (await page.request.get("/api/graph")).json();
 expect(graph.nodes).toHaveLength(2);
 expect(graph.edges).toHaveLength(1);
 expect(graph.edges[0].source).toBe("explicit");
 await page.getByRole("button", { name: "Close panel" }).click();
 await page.getByRole("button", { name: "Fit graph", exact: true }).click();
 // With exactly two nodes, the sole segment passes through the viewport center.
 const canvas = page.getByLabel("Interactive knowledge graph");
 const box = await canvas.boundingBox();
 expect(box).not.toBeNull();
 await page.mouse.click(box!.x + box!.width / 2, box!.y + box!.height / 2);
 await expect(page.locator(".edge-panel h2")).toHaveText("Relationship");
 await expect(page.locator(".edge-panel")).toContainText("Explicit link");
 await page.getByRole("button", { name: "Close panel" }).click();
 await page.getByLabel("Search notes", { exact: true }).fill("E2E Alpha");
 await page.getByRole("button", { name: /E2E Alpha title/ }).click();
 await page.getByRole("button", { name: "Edit", exact: true }).click();
 await page.getByLabel("Note title", { exact: true }).fill("E2E Renamed");
 await page.getByRole("button", { name: "Save", exact: true }).click();
 await expect(page.locator(".inspector h2")).toHaveText("E2E Renamed");
 await expect(page.locator("pre.content")).not.toContainText("# E2E Alpha");
 await expect(page.locator("pre.content")).toContainText("# E2E Renamed");
 // Focusing centers the selected node, so drag and unpin can use real pointer input.
 const focusedBox = (await canvas.boundingBox())!;
 const cx = focusedBox.x + focusedBox.width / 2, cy = focusedBox.y + focusedBox.height / 2;
 await page.mouse.move(cx, cy); await page.mouse.down(); await page.mouse.move(cx + 60, cy + 40, { steps: 6 }); await page.mouse.up();
 const alphaID = graph.nodes.find((n: { title: string }) => n.title === "E2E Alpha").id;
 await expect.poll(async () => (await (await page.request.get(`/api/nodes/${alphaID}`)).json()).x).not.toBeNull();
 await page.mouse.dblclick(cx + 60, cy + 40);
 await expect.poll(async () => (await (await page.request.get(`/api/nodes/${alphaID}`)).json()).x).toBeNull();
 await page.getByRole("button", { name: "Edit", exact: true }).click();
 const alpha = graph.nodes.find((n: { title: string }) => n.title === "E2E Alpha");
 await page.request.put(`/api/notes/${alpha.id}`, { data: { title: "E2E Renamed", content: "# E2E Renamed\n\nExternal content" } });
 await page.getByLabel("Markdown content").fill("My unsaved draft");
 await page.getByRole("button", { name: "Save", exact: true }).click();
 await expect(page.locator(".editor [role=alert]")).toContainText("note changed");
 await expect(page.getByLabel("Markdown content")).toHaveValue("My unsaved draft");
 page.once("dialog", dialog => dialog.accept());
 await page.getByRole("button", { name: "Cancel", exact: true }).click();
 await page.getByRole("button", { name: "Sync", exact: true }).click();
 await expect(page.locator("pre.content")).toContainText("External content");
 await page.getByRole("button", { name: "Settings & tools" }).click();
 await page.getByLabel("Filter by tag").fill("test");
 await expect(page.getByRole("region", { name: "Search results" })).toContainText("No matching notes");
 await page.getByRole("button", { name: "Clear filters" }).click();
 await page.getByLabel("Automatic edge threshold").fill("10");
 await page.getByRole("button", { name: "Save settings" }).click();
 await expect.poll(async () => (await (await page.request.get("/api/settings")).json()).min_auto_edge_strength).toBe(10);
 await page.getByLabel("Import vault").setInputFiles({ name: "imported.md", mimeType: "text/markdown", buffer: Buffer.from("# Imported\n\n#fresh") });
 await page.getByRole("button", { name: "Import 1 notes", exact: true }).click();
 await expect(page.locator(".status")).toContainText("Imported 1 notes");
 await page.getByRole("button", { name: "Settings & tools" }).click();
 await page.getByRole("button", { name: "Close panel" }).click();
 await page.getByRole("button", { name: "Undo", exact: true }).click();
 await expect.poll(async () => (await (await page.request.get("/api/notes")).json()).length).toBe(2);
 await page.getByRole("button", { name: "Redo", exact: true }).click();
 await expect.poll(async () => (await (await page.request.get("/api/notes")).json()).length).toBe(3);
 await page.setViewportSize({ width: 390, height: 844 });
 await expect(canvas).toBeVisible();
 expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
 await page.getByLabel("Show weak links").check();
 await page.screenshot({ path: "test-results/v1-mobile.png" });
 await page.setViewportSize({ width: 1280, height: 800 });
 await page.screenshot({ path: "test-results/v1-desktop.png" });
 expect(errors).toEqual([]);
});

test("Activity dashboard controls stay local, persist pause, and validate privacy settings", async ({ page }) => {
 await page.goto("/");
 await page.getByRole("button", {name:/^Activity [●○]$/}).click();
 await expect(page.getByRole("region",{name:"Activity dashboard"})).toBeVisible();
 await expect(page.getByRole("heading",{name:"What you use"})).toBeVisible();
 await expect(page.getByText("Recording stopped",{exact:false})).toBeVisible();
 await expect(page.getByRole("img",{name:"App usage by period"})).toBeVisible();
 await page.getByText("View chart data table",{exact:true}).click();
 await expect(page.locator(".chart-table table")).toContainText("No usage");
 await page.getByText("View chart data table",{exact:true}).click();
 const dailySeries=await (await page.request.get("/api/activity/series?days=7&granularity=day")).json();
 expect(dailySeries.buckets).toHaveLength(7);
 await page.getByLabel("Chart granularity").selectOption("week");
 await expect(page.locator(".comparison-heading p")).toContainText("Weekly totals");
 await expect(page.locator(".comparison")).toContainText("Weeks at the range boundaries may be partial");
 await page.getByRole("button",{name:"Active vs idle"}).click();
 await expect(page.getByRole("img",{name:"Active and idle time by period"})).toBeVisible();
 await page.getByRole("button",{name:"Context switches"}).click();
 await expect(page.getByRole("img",{name:"Context switches by period"})).toBeVisible();
 await page.getByLabel("Activity time range").selectOption("30");
 await expect(page.locator(".comparison-heading p")).toContainText("Weekly totals");
 await page.getByText("Privacy, retention & browser setup",{exact:true}).click();
 await page.getByLabel("Idle threshold",{exact:true}).fill("90");
 await page.getByLabel("Excluded domains",{exact:true}).fill("private.example");
 await page.getByRole("button",{name:"Save tracking settings"}).click();
 await expect.poll(async()=> (await (await page.request.get("/api/activity")).json()).config.idle_seconds).toBe(90);
 const status=await (await page.request.get("/api/activity")).json();
 expect(status.config.enabled).toBe(false);
 expect(status.config.excluded_domains).toEqual(["private.example"]);
 await page.getByRole("button",{name:"Show browser pairing token"}).click();
 await expect(page.getByLabel("Browser pairing token",{exact:true})).toHaveValue(/^[a-f0-9]{64}$/);
 await page.getByRole("button",{name:"Close activity"}).click();
 await page.reload();
 await expect(page.getByText("○ Activity stopped",{exact:true})).toBeVisible();
});
